name: Keep Alive

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
    - name: Ping Server
      run: |
        curl -sSf "${{ secrets.REPLIT_URL }}" > /dev/null
